// @ts-check
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/.venv/**',
      'packages/ts-client/src/generated/**',
      // Generated by `next build`; not ours to lint.
      'apps/web/next-env.d.ts',
      'apps/web/.next/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.strictTypeChecked,
  {
    languageOptions: {
      parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname },
    },
    rules: {
      // Repository convention: no `any` — use `unknown` and narrow.
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/consistent-type-imports': 'error',
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    },
  },
  {
    // Build config files run under Node, not in the browser, and are not part
    // of any tsconfig project, so type-aware linting cannot apply to them.
    files: ['**/*.config.{js,mjs,cjs,ts}'],
    // Spread first: disableTypeChecked carries its own languageOptions and
    // would otherwise clobber the globals set here.
    ...tseslint.configs.disableTypeChecked,
    languageOptions: {
      ...tseslint.configs.disableTypeChecked.languageOptions,
      globals: { process: 'readonly', __dirname: 'readonly', module: 'writable' },
    },
  },
  {
    // Next.js app router: browser + React globals.
    files: ['apps/web/**/*.{ts,tsx}'],
    languageOptions: {
      globals: { window: 'readonly', document: 'readonly', fetch: 'readonly', React: 'readonly' },
    },
  },
  prettier,
);
